substituters = https://cache.nixos.org
trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
experimental-features = nix-command flakes
extra-experimental-features = nix-command flakes
accept-flake-config = true
trusted-users = root ironcladdev
