substituters = https://cache.nixos.org https://4473-sh.cachix.org
trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= 4473-sh.cachix.org-1:5Pf9PVXNPt/06ikHrBXi5LxpAZ318RFH+5Fy0Cv62Ss=
experimental-features = nix-command flakes
extra-experimental-features = nix-command flakes
accept-flake-config = true
trusted-users = root ironcladdev
