# Text
font_family      JetBrainsMono NFM
bold_font        JetBrainsMono NFM
italic_font      JetBrainsMono NFM
bold_italic_font JetBrainsMono NFM
modify_font cell_height 120%
modify_font cell_width 100%
font_size 10.0
disable_ligatures always

# Cursor
cursor #C8D5F1
cursor_text_color #1F1D2D
cursor_trail 1
cursor_trail_decay 0.1 0.4
cursor_trail_start_threshold 1

# Shell
shell fish
shell_integration enabled

# Scrollback
scrollback_lines 5000
scrollback_pager nvim --cmd 'set eventignore=FileType' +'nnoremap q ZQ' +'call nvim_open_term(0, {})' +'set nomodified nolist number relativenumber' +'$' -

# Allow programs to write the clipboard via OSC 52
clipboard_control write-clipboard write-primary

# Tab Bar
tab_bar_edge top
tab_bar_style powerline
tab_powerline_style slanted

# Tab Settings
active_tab_foreground   #1F1D2D
active_tab_background   #C9DE96
active_tab_font_style   bold-italic
inactive_tab_foreground #949BB9
inactive_tab_background #1F1D2D
inactive_tab_font_style normal

# Colors
foreground #C8D5F1
background #1F1D2D
background_opacity 0.8
dynamic_background_opacity yes
color0 #747A9C
color8 #747A9C
color1 #CA5072
color9 #E55376
color2  #B3C48D
color10 #C9DE96
color3  #CDBB91
color11 #E9D39C
color4  #8CAAD1
color12 #9ABFE8
color5  #C091D0
color13 #D0A1E8
color6  #8CAAD1
color14 #9ABFE8
color7  #949BB9
color15 #C8D5F1

# Split Layout
enabled_layouts splits

# Shortcut Settings
clear_all_shortcuts yes

# SSH
allow_remote_control yes
share_connections yes
forward_remote_control yes

# Keybindings

## Tmux-like keybindings for splits
map ctrl+t>ctrl+t launch --location=vsplit --cwd=current
map ctrl+t>ctrl+s launch --location=hsplit --cwd=current
map ctrl+t>ctrl+o neighboring_window right
map ctrl+t>ctrl+n neighboring_window left
map ctrl+t>ctrl+e neighboring_window down
map ctrl+t>ctrl+i neighboring_window up
map ctrl+, resize_window narrower 2
map ctrl+. resize_window wider 2

### Basic tab management
map ctrl+t>c new_tab_with_cwd
map ctrl+t>ctrl+c new_tab
map ctrl+t>w close_window_with_confirmation
map ctrl+t>p previous_tab
map ctrl+t>n next_tab

## Scrollback
map ctrl+t>s show_scrollback

## Scrolling
map ctrl+u scroll_page_up
map ctrl+d scroll_page_down
map ctrl+e scroll_line_down
map ctrl+y scroll_line_up

## Reload config
map ctrl+t>ctrl+r load_config_file

## Zooming
map ctrl+equal change_font_size all +2.0
map ctrl+minus change_font_size all -2.0

## Copying/Pasting
map ctrl+insert copy_to_clipboard
map shift+insert paste_from_clipboard
