require("config.lsp.servers.ts_ls")
require("config.lsp.servers.lua_ls")
require("config.lsp.servers.html")
require("config.lsp.servers.cssls")
require("config.lsp.servers.astro")
require("config.lsp.servers.rust_analyzer")
