hl.on("hyprland.start", function()
	hl.dispatch(hl.dsp.exec_cmd("signal-desktop", { workspace = "2" }))
	hl.dispatch(hl.dsp.exec_cmd('omarchy-launch-webapp "https://discord.com/channels/@me"', { workspace = "2" }))
	hl.dispatch(hl.dsp.exec_cmd('omarchy-launch-webapp "https://mail.google.com"', { workspace = "2" }))
	hl.dispatch(hl.dsp.exec_cmd("omarchy-launch-browser", { workspace = "3" }))
	hl.dispatch(hl.dsp.exec_cmd("kitty", { workspace = "1" }))
	hl.dsp.focus({ workspace = "1" })
end)
