hl.on("hyprland.start", function()
	-- hl.dispatch(hl.dsp.exec_cmd("uwsm-app -- hypridle"))
	-- hl.dispatch(hl.dsp.exec_cmd("uwsm-app -- mako"))
	-- hl.dispatch(hl.dsp.exec_cmd("uwsm-app -- waybar"))
	-- hl.dispatch(hl.dsp.exec_cmd("uwsm-app -- fcitx5 --disable notificationitem"))
	-- hl.dispatch(hl.dsp.exec_cmd("swaybg -i ~/.config/wallpapers/wallpaper-ak.png -m fill"))

	hl.dispatch(hl.dsp.exec_cmd("signal-desktop", { workspace = "2" }))
	hl.dispatch(hl.dsp.exec_cmd('brave --app="https://app.slack.com/client/T03UDTQT274/C03U79SLQNA" --new-window', { workspace = "2" }))
	hl.dispatch(hl.dsp.exec_cmd('brave --app="https://mail.google.com" --new-window', { workspace = "2" }))
	hl.dispatch(hl.dsp.exec_cmd('brave --app="https:app.clickup.com" --new-window', { workspace = "2" }))
	hl.dispatch(hl.dsp.exec_cmd("brave", { workspace = "3" }))
	hl.dispatch(hl.dsp.exec_cmd("spotify", { workspace = "4" }))
	hl.dispatch(hl.dsp.exec_cmd("kitty", { workspace = "1" }))
	hl.dsp.focus({ workspace = "1" })
end)
