general {
    ignore_empty_input = true
}

background {
    monitor =
    path = ~/.config/wallpapers/lock-screen.png
    brightness = 0.25
}

animations {
    enabled = false
}

input-field {
    monitor =
    size = 480, 64
    position = 0, 0
    halign = center
    valign = center

    inner_color = rgba(36, 35, 54, 1.0)
    outer_color = rgba(53, 53, 83, 1.0)
    check_color = rgba(233, 211, 156, 1.0)
    fail_color = rgba(229, 83, 118, 1.0)
    outline_thickness = 2
    swap_font_color = true

    font_family = JetBrainsMono NFM
    font_color = rgba(148, 155, 185, 1.0)
    dots_text_format = *

    placeholder_text = [sudo] password for $USER:

    check_text = [checking...]
    fail_text = [incorrect] ($ATTEMPTS)

    rounding = 0
    shadow_passes = 0
    fade_on_empty = false
}

label {
    monitor =
    position = 0, 120
    text = $TIME
    font_size = 24
    color = rgba(200, 213, 241, 1.0)
}

auth {
    fingerprint:enabled = false
}
